In [10]:
class Point:
    def __init__(self, c, d):
        num1 = c
        num2 = d
    def show(self):
        print("({0:d},{1:d})".format(num1, num2))
    


In [40]:
import csv
f = open('C:\seoul.csv')
data = csv.reader(f)
header = next(data)
max_temp = 999
max_date = ''
temp = 0
count = 0
for row in data:
    if row[-1] == '':
        row[-1] = 999
    if row[-2] == '':
        row[-2] = 999
    row[-1] = float(row[-1])
    row[-2] = float(row[-2])
    
    
    if count == 6:
        if max_temp > temp:
            max_date = row[0]
            max_temp = temp

        count = 0
        temp = 0
    else:
        temp += row[-1] - row[-2]
        count = count + 1
   
f.close()


str = '{0:s}/{1:s}'.format(max_date.split('-')[1],max_date.split('-')[2])
i = int(max_date.split('-')[2]) - 7
str2 = '{0:s}/{1:d}'.format(max_date.split('-')[1], i)
print('Max Week = ', str2, '~', str)



Max Week =  05/14 ~ 05/21


In [34]:
import matplotlib.pyplot as plt
import numpy as np
a = np.array({1,1,0,1,0,1,1,1,1,0,1,0,1,1,0,1,0,0})
docs = np.array([1,1,0,1,0,1,1,1,1,0,1,0,1,1,0,1,0,0]).reshape(3,6)
print(docs)

query = np.array([1,1,0,0,1,0,])
print(query)

c = np.dot(query,docs.T)



[[1 1 0 1 0 1]
 [1 1 1 0 1 0]
 [1 1 0 1 0 0]]
[1 1 0 0 1 0]
[2 3 2]
